### ISSUE TITLE
Update our goglide image to use go v1.9.0

### ISSUE THREAD

**Issue by alika** [samsung-cnct/golang-tools#19]

**Comment by mikeln** [comment]
Forgot to mention this... check the version that the latest Kubernetes is built with.  We want to be in step with them if possible.

**Comment by alika** [comment]
👍 will do

**Comment by alika** [comment]
Manually deployed this quay.io [here](https://quay.io/repository/samsung_cnct/goglide). Setup quay.io local cli access. Had to get quay.io write/repo permissions for samsung-cnct repos on quay.
