### ISSUE TITLE
Add clarification in build.sh, and Jenkinsfile corrections

### ISSUE THREAD

**Issue by oneilcin** [samsung-cnct/golang-tools#27]
In build.sh clarify the path needed for go_dir.  Also make it clear that if you have go tools installed for building on your mac (OSX) the GOPATH needs to be separate from the GOPATH for linux development.

In Jenkinsfile, correct the directory for containerize and push.  Also separate out the vet stages to vet and lint.  

I'm thinking we should comment out the gosimple test too, what do you think?

**Comment by oneilcin** [comment]
This is for the example-project

**Comment by mikeln** [comment]
This type of stuff should be put in the README.md setup documentation (i.e. what to change when you copy this stuff into a new project).

The example-project itself is setup to run in place to validate it still works.  Comments should be added to the Jenkinsfile to indicate the location(s) and most likely change that will be needed.   

Separating vet and lint is ok.  Gosimple should stay.

**Comment by oneilcin** [comment]
Lots of typos in the Makefiles, should be fixed. See comments on https://github.com/samsung-cnct/golang-tools/issues/27

**Comment by oneilcin** [comment]
new PR #28
