### ISSUE TITLE
Create an Example golang Project Setup

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/golang-tools#3]
Create an Example golang Project Setup for new projects to start with.

README
DEVELOPMENT
Makefile
build.sh
make.golang

Explain structure, and which tools to use and why.
requirements for consideration of a clean build etc.

**Comment by mikeln** [comment]
Initial stuff created under /example-project.

Missing things: 
1) main go app
2) any example of Cobra/Viper /cmd dir example
3) jenkins file
4) /_containterized/  dir example for creating a docker container of the given app

**Comment by mikeln** [comment]
Added example main.go using Corbra/viper in /cmd subdir
added _containerize dir

**Comment by coffeepac** [comment]
also add preferred golang testing style, should be in the makefile as a target.

**Comment by samba** [comment]
@mikeln @coffeepac What else do we still need to accomplish here?

- [ ] Examples of cobra/viper to properly handle config/args/environ 
- [ ] Jenkins file for common build configuration
- [ ] A more robust Go app? Maybe link to [samsung-cnct/technical-on-boarding](/samsung-cnct/technical-on-boarding) suffices?

@notjames anything you're working on relates?

**Comment by notjames** [comment]
I'm still wrapping my head around cobra on some things. I couldn't even get some of their examples to work for flags (https://github.com/spf13/cobra) under positional and custom arguments (example) -- so that sorta concerns me. But I wouldn't be surprised if it was user-error.

**Comment by notjames** [comment]
Oh, I think linking to the on-boarding app is sufficient for a good example...for now until we learn better examples.

**Comment by mikeln** [comment]
You can look at almost any Kubernetes app for some example uses of Cobra.  However, kubectl in Kubernetes proper did a lot of "by hand" coding (vs using the Cobra generated code).   kubernetes/helm used to be a good example...as it is a newer creation.  Or you could reference our K8os Monkey project (barrel).

**Comment by mikeln** [comment]
I've fixed the example-project  all to compile etc mostly correctly.

Just realize that any of these examples are really just starting point guidelines...

**Comment by coffeepac** [comment]
items left:
An example Jenkinsfile

if more, please add them explicitly here.

**Comment by samba** [comment]
[Good example][1] of viper/cobra integration, per @davidewatson. Any template project we rely on should probably provide a similar baseline integration.

[1]: https://github.com/samsung-cnct/careen/blob/c2212252557d0edf6ed0fdae549b98c42aca419a/cmd/root.go#L98

**Comment by mikeln** [comment]
currently working through creating a good golang build jenkins file.

**Comment by mikeln** [comment]
jenkins file created.

**Comment by mikeln** [comment]
put this on the backburner for a while again.

**Comment by coffeepac** [comment]
this requires constant improvement but we no longer need a focused effort.
